Feature diplom2
dymont78/WomenDress2 pull request #2
Opened 2021-07-22 21:38 UTC by dymont78

2021-07-23 20:08 UTC, vchesnakoutest requested changes
please make fixes

2021-07-23 20:08 UTC, vchesnakoutest commented on pom.xml
> +<!--            <scope>test</scope>-->
тут лучше не закоменчивать, а просто удалить

2021-07-23 20:08 UTC, vchesnakoutest commented on src/main/java/pages/CartModalPage.java
> +    @Step("Verify product Qti '{productQty}' before adding in cart")
Verify product Qty....

2021-07-23 20:08 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public static final String DELETE_FROM_CART_BUTTON = "//*[text() = '%s']/ancestor::tr/*[@class = 'cart_delete text-center']";
cart_delete text-center - попробуй оставить что-то одно

2021-07-23 20:08 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +        return  this;
два пробела после return

2021-07-23 20:08 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public static final String FIEAD_QTY = "//*[text() = '%s']/ancestor::tr//input[@type = 'text']";
FIELD_QTY

2021-07-23 20:08 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public static final By BUTTON_CART_PROCEED_TO_CHECKOUT_STEP4 = By.xpath("//button[@name= 'processCarrier']");
это уже не элементы страницы CartPage, для них надо создавать отдельные классы страниц

2021-07-23 20:08 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public static final By FINAL_PRICE = By.xpath("//span[@class = 'price']");
тоже самое, все эти элементы надо выность на отдельыне страницы.  это уже не корзина

2021-07-23 20:08 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    }
методы тоже надо выносить на другие соответствующие функционалу страницы.

2021-07-23 20:08 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public double convertStringToDouble (String stringPrice) {
removeDollarSignFromString. Т.к. этот метод утилитный, давай для него создадим отдельный пакет utils, в нем класс Utils. Метод этот можно сделать статическим, чтобы вызывать его без объявления экземпляра класса.

2021-07-24 06:04 UTC, dymont78 commented on pom.xml
> +<!--            <scope>test</scope>-->
ok

2021-07-24 06:05 UTC, dymont78 commented on src/main/java/pages/CartModalPage.java
> +    @Step("Verify product Qti '{productQty}' before adding in cart")
ok

2021-07-24 07:42 UTC, dymont78 commented on src/main/java/pages/CartPage.java
> +    public static final String DELETE_FROM_CART_BUTTON = "//*[text() = '%s']/ancestor::tr/*[@class = 'cart_delete text-center']";
ok

2021-07-24 07:42 UTC, dymont78 commented on src/main/java/pages/CartPage.java
> +        return  this;
ok

2021-07-24 07:44 UTC, dymont78 commented on src/main/java/pages/CartPage.java
> +    public static final String FIEAD_QTY = "//*[text() = '%s']/ancestor::tr//input[@type = 'text']";
ok

2021-07-24 07:49 UTC, dymont78 commented on src/main/java/pages/CartPage.java
> +    public double convertStringToDouble (String stringPrice) {
ok

2021-07-24 08:22 UTC, dymont78 commented on src/main/java/pages/CartPage.java
> +    public static final By BUTTON_CART_PROCEED_TO_CHECKOUT_STEP4 = By.xpath("//button[@name= 'processCarrier']");
ok

2021-07-24 08:22 UTC, dymont78 commented on src/main/java/pages/CartPage.java
> +    public static final By FINAL_PRICE = By.xpath("//span[@class = 'price']");
ok

2021-07-24 08:22 UTC, dymont78 commented on src/main/java/pages/CartPage.java
> +    }
ok

2021-07-24 17:04 UTC, vchesnakoutest approved these changes

2021-07-24 20:58 UTC, merged